### import the module you need first

In [23]:
import numpy as np

## step1. 
#### Construct a numpy array represent the equations.
#### the coefficients,answers and augmented matrix of each equation need to be stored separately.

In [24]:
"""
example:
 
5y-7z = 7        | 0 5 -7 7 |
4x-z = 8      -> | 4 0 -1 8 |
x-y+z = 9        | 1 -1 1 9 |
"""
#construct an array 
#with float type
arr = np.array([[0, 5, -7, 7], 
                [4, 0, -1, 8], 
                [1, -1, -1, 9]],float)
print (arr)

[[ 0.  5. -7.  7.]
 [ 4.  0. -1.  8.]
 [ 1. -1. -1.  9.]]


## step2. 
### Before doing gauss elimination,
### we need to check if the first element([0,0]) of the augmented matrix is zero or not.
### If the first element is zero,
### we need to find another row whose first element isn't zero,and change them.

In [25]:
#preprocess
#check [0,0] 
for i in range(3):
    if(arr[0,0] == 0): #if first element is zero, change the row
        arr[[0,i]] = arr[[i,0]] #swap

In [26]:
#test:step2
#print the new augment matrixz
print(arr)

[[ 4.  0. -1.  8.]
 [ 0.  5. -7.  7.]
 [ 1. -1. -1.  9.]]


## step3. gauss elimination

#### print the matrix after  gauss elimination

In [27]:
def GaussElimination(A):
    arr = A
    n = arr.shape[0] #get num of rows
    for i in range(n):
        for j in range(i+1, n): #echelon form
            if(arr[j][i]!=0):  #check   
                p = arr[j][i]/arr[i][i] # get ratio
                #row to row operation
                for k in range(n+1): #scan columns
                    arr[j][k] = arr[j][k] - p*arr[i][k] 
    return arr

In [28]:
#test:step3
#print the augment matrix after gauss elimination

print("the augment matrix after gauss elimination :\n")   
print(GaussElimination(arr))

the augment matrix after gauss elimination :

[[ 4.    0.   -1.    8.  ]
 [ 0.    5.   -7.    7.  ]
 [ 0.    0.   -2.15  8.4 ]]


## step4. LU decomposition(bonus)

## if you don't want to submit bouns,you don't need to do  step4 and step5

In [29]:
def LU(A):
    
    U = A 
    n = U.shape[0] #get num. of row
    L = np.zeros([n,n]) #construct 2D zero array 
    
    #check and avoid first element being zero
    for i in range(n):
        if(U[0,0] == 0):
            U[[0,i]] = U[[i,0]]
    #diagonal of L must be 1
    for i in range(n):
        L[i][i] = 1
    #use gauss elimination and complete of L&U
    for i in range(n):
        for j in range(i+1, n):
            if(U[j][i]!=0):    
                p = U[j][i]/U[i][i] #ratio
                L[j][i] = p
                #row to row operation
                for k in range(n):
                    U[j][k] = U[j][k] - p*U[i][k]
    return L, U

In [30]:
#print L and U
#construct an array 
#with float type
A = np.array([[0, 5, -7], 
              [4, 0, -1], 
              [1, -1, -1]],float)
Lower, Upper = LU(A)
print("L: ")
print(Lower)
print("U: ")
print(Upper)

L: 
[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.25 -0.2   1.  ]]
U: 
[[ 4.    0.   -1.  ]
 [ 0.    5.   -7.  ]
 [ 0.    0.   -2.15]]


## step5. check the ansewer of LU(bonus)

please use the function in scipy.linalg to check your answer

the documentatin of scipy.linalg :
https://docs.scipy.org/doc/scipy/reference/linalg.html

In [31]:
import scipy.linalg as la

In [32]:
A = np.array([[0, 5, -7], 
              [4, 0, -1], 
              [1, -1, -1]],float)
P, L, U = la.lu(A)
print("L:")
print(L)
print("U:")
print(U)

L:
[[ 1.    0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.25 -0.2   1.  ]]
U:
[[ 4.    0.   -1.  ]
 [ 0.    5.   -7.  ]
 [ 0.    0.   -2.15]]
